using System.Collections.Concurrent;
using System.Runtime.InteropServices;
using System;
using System.Threading;
using System.Threading.Tasks;
using PortAudioSharp;
using SherpaOnnx;



class KokoroTtsPlayService
{
    private static OfflineTts tts = null!;
    private static int DeviceIndex=0;
    private static StreamParameters streamParam;

    static void InitTTS()
    {
        var config = new OfflineTtsConfig();
        config.Model.Kokoro.Model = "./kokoro/model.onnx";
        config.Model.Kokoro.Voices = "./kokoro/voices.bin";
        config.Model.Kokoro.Tokens = "./kokoro/tokens.txt";
        config.Model.Kokoro.DataDir = "./kokoro/espeak-ng-data";
        config.Model.Kokoro.Lexicon = "./kokoro/lexicon-us-en.txt,./kokoro/lexicon-zh.txt";

        config.Model.NumThreads = 2;
        config.Model.Debug = 0;
        config.Model.Provider = "cpu";

        tts = new OfflineTts(config);
    }

    static void SetOutputDevice(bool bPrintList = true)
    {
        PortAudio.Initialize();

        if (bPrintList)
        {
            Console.WriteLine(PortAudio.VersionInfo.versionText);
            Console.WriteLine($"Number of devices: {PortAudio.DeviceCount}");
            for (int i = 0; i != PortAudio.DeviceCount; ++i)
            {
                Console.WriteLine($" Device {i}");
                DeviceInfo deviceInfo = PortAudio.GetDeviceInfo(i);
                Console.WriteLine($"   Name: {deviceInfo.name}");
                Console.WriteLine($"   Max output channels: {deviceInfo.maxOutputChannels}");
                Console.WriteLine($"   Default sample rate: {deviceInfo.defaultSampleRate}");
            }
        }

        DeviceIndex = PortAudio.DefaultOutputDevice;
        if (DeviceIndex == PortAudio.NoDevice)
        {
            Console.WriteLine("No default output device found. Please use ../offline-tts instead");
            Environment.Exit(1);
        }

        var info = PortAudio.GetDeviceInfo(DeviceIndex);

        ConsoleColor oc = Console.ForegroundColor;
        Console.ForegroundColor = ConsoleColor.Green;
        Console.WriteLine("================================================================");
        Console.WriteLine($"TTS Output device : [{DeviceIndex}] {info.name}");
        Console.WriteLine("----------------------------------------------------------------");
        Console.ForegroundColor = oc;

        var param = new StreamParameters();
        param.device = DeviceIndex;
        param.channelCount = 1;
        param.sampleFormat = SampleFormat.Float32;
        param.suggestedLatency = info.defaultLowOutputLatency;
        param.hostApiSpecificStreamInfo = IntPtr.Zero;

        streamParam = param;
    }

    static async Task TestTTS()
    {
        var text = "中英文语音合成测试。This is generated by next generation Kaldi using Kokoro without Misaki. 你觉得中英文说的如何呢？豆包的编程能力一般般，简单的还可以，遇到复杂的，就胡编乱造。";
        Console.WriteLine($" TTS Test: {text}");
        await TTSQueue.StartTTSPlay(55, text, 1.0f, false);


        text = "这是第二段中文语音测试，GroupM是中国最大的广告媒介代理公司。";
        Console.WriteLine($" TTS Test: {text}"); 
        await TTSQueue.StartTTSPlay(33, text, 1.2f);

        text = "这是第三段中文语音测试，盛世长城国际广告是中国最早的广告公司。薇薇安是盛世长城最漂亮的女孩子";
        Console.WriteLine($" TTS Test: {text}");
        await TTSQueue.StartTTSPlay(85, text, 1.2f);
    }

    static void TestTTSQueue()
    {
        TTS_Item ex1 = new TTS_Item("Test", 55, "这是第一段中英文语音合成测试。This is generated by next generation Kaldi using Kokoro without Misaki. 你觉得中英文说的如何呢？豆包的编程能力一般般，简单的还可以，遇到复杂的，就胡编乱造。", 1.0f, false);
        TTSQueue.Append(ex1);

        TTS_Item ex2 = new TTS_Item("Test", 33, "这是第二段中文语音测试，GroupM是中国最大的广告媒介代理公司。", 1.2f, true);
        TTSQueue.Append(ex2);

        TTS_Item ex3 = new TTS_Item("Test", 85, "这是第三段中文语音测试，盛世长城国际广告是中国最早的广告公司。薇薇安是盛世长城最漂亮的女孩子", 1.2f, true);
        TTSQueue.Append(ex3);
    }
    static async Task Main(string[] args)
    {
        SetOutputDevice(false);
        InitTTS();
        Thread.Sleep(5000); // wait for monitor to start

        TTSQueue.Init(tts, streamParam);
        await TTSQueue.StartMonitor();
        

        bool isInternalTesting = false;
        if (isInternalTesting)
        {
            //await TestTTS();
            TestTTSQueue();

            while (true)
            {
                Console.ReadLine();
            }
            //await Task.WhenAll();
            //Console.WriteLine("Game Over");
        }
        else
        {
            TTS_UdpListener udp = new TTS_UdpListener();
            await udp.StartListeningAsync();
        }
    }
}
